---
abstract: 'Generate and manipulate HTML as native Perl data structures'
author:
  - 'Michael Brown <mbrown@fensystems.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Native
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Carp::Clan: 0
  Exporter: 0
  HTML::Entities: 0
  List::Util: 0
  Scalar::Util: 0
  perl: 5.9.5
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.0
